pyinstaller --onedir --windowed `
  --name Anuvad `
  --icon=assets/images/icon.ico `
  --add-data "app.cfg;." `
  --add-data "assets;assets" `
  --collect-data indic_transliteration `
  --hidden-import indic_transliteration `
  --exclude-module "pytest" `
  --exclude-module "pytest-cov" `
  --exclude-module "unittest" `
  --exclude-module "tests" `
  --exclude-module "doc" `
  --exclude-module "unused_locale" `
  --exclude-module "beautifulsoup4" `
  --exclude-module "pyflakes" `
  --exclude-module "flake8" `
  --exclude-module "pycodestyle" `
  --exclude-module "soupsieve" `
  --exclude-module "PyQt5.QtWebEngine" `
  --exclude-module "PyQt5.QtWebEngineWidgets" `
  --exclude-module "PyQt5.QtNetworkAuth" `
  --exclude-module "PyQt5.QtCharts" `
  --exclude-module "PyQt.QtDataVisualization" `
  main.py